# enviroment desktop
# created by Markus Bader <markus.bader@tuwien.ac.at>

ARG OWNER=registry.auto.tuwien.ac.at/roblab/docker/focal/noetic
ARG BASE_CONTAINER=$OWNER-enviroment-ide
FROM $BASE_CONTAINER

USER root

ENV MY_PRJ=${MY_HOME}/projects/ros/mr

USER root
RUN apt-get update
RUN apt install -y \
    ros-${ROS_DISTRO}-amcl \
    ros-${ROS_DISTRO}-ros-base \
    ros-${ROS_DISTRO}-gmapping \
    ros-${ROS_DISTRO}-tf \
    ros-${ROS_DISTRO}-teleop-twist-keyboard \
    ros-${ROS_DISTRO}-marker-msgs \
    ros-${ROS_DISTRO}-map-server \
    ros-${ROS_DISTRO}-move-base  \
    ros-${ROS_DISTRO}-navigation \
    ros-${ROS_DISTRO}-rviz  \
    ros-${ROS_DISTRO}-rqt-reconfigure \
	ros-${ROS_DISTRO}-rqt-common-plugins \
    ros-${ROS_DISTRO}-slam-gmapping \
    ros-${ROS_DISTRO}-stage \
    git tmux vim wget gzip iputils-ping
    
USER ${MY_USER}

RUN mkdir -p ${MY_PRJ}/ws00/src/
COPY --chown=${MY_USER}:${MY_USER} ./utils/stage_ros-20.04.tar.gz ${MY_PRJ}/ws00/src/
RUN cd ${MY_PRJ}/ws00/src &&  \
	tar -xzvf stage_ros-20.04.tar.gz &&  \
	/bin/bash -c 'source /opt/ros/${ROS_DISTRO}/setup.bash;  cd ${MY_PRJ}/ws00; catkin_make'
	
RUN mkdir -p ${MY_PRJ}/tuw/src/
COPY --chown=${MY_USER}:${MY_USER} ./utils/mr2021.tar.gz ${MY_PRJ}/tuw/src/
RUN cd ${MY_PRJ}/tuw/src &&  \
	tar -xzvf mr2021.tar.gz  &&  \
	/bin/bash -c 'source ${MY_PRJ}/ws00/devel/setup.bash;  cd ${MY_PRJ}/tuw; catkin_make -DCMAKE_BUILD_TYPE=Debug'
	
RUN touch ${MY_PRJ}/env.sh && \  
    chmod +x ${MY_PRJ}/env.sh && \ 
    echo 'source /opt/ros/noetic/setup.bash' >> ${MY_PRJ}/env.sh  && \   
    echo 'echo "** ROS /opt/ros/noetic/setup.bash initialized **"' >> ${MY_PRJ}/env.sh  && \   
    echo 'source $HOME/projects/ros/mr/ws00/devel/setup.bash' >> ${MY_PRJ}/env.sh  && \  
    echo 'source $HOME/projects/ros/mr/tuw/devel/setup.bash'  >> ${MY_PRJ}/env.sh

RUN echo "catkin_make -DCMAKE_BUILD_TYPE=Debug" >> ~/.bash_history   &&  \
	echo "rosrun rqt_reconfigure rqt_reconfigure" >> ~/.bash_history   &&  \
	echo "roslaunch stage_ros world.launch world:=line.world" >> ~/.bash_history   &&  \
	echo "roslaunch mr_local_planner planner.launch world:=line.world mode:=1" >> ~/.bash_history   &&  \
	echo "roslaunch stage_ros world.launch world:=cave.world" >> ~/.bash_history   &&  \
	echo "roslaunch mr_local_planner planner.launch stage:=1 world:=cave.world mode:=1" >> ~/.bash_history  &&  \
	echo "tmux new -s mpn \; split-window -v \; split-window -v \; select-pane -t 0 \; split-window -v \; select-pane -t 0 \; split-window -h \; select-pane -t 0 \; attach" >> ~/.bash_history

COPY --chown=${MY_USER}:${MY_USER} ./mr.md ${MY_PRJ}/readme.md
USER root
# clean apt
RUN rm -rf /var/lib/apt/lists/*

USER ${MY_USER}
WORKDIR ${MY_PRJ}
ENV HOME ${MY_HOME}
CMD /bin/bash

