# enviroment desktop
# created by Markus Bader <markus.bader@tuwien.ac.at>

ARG UBUNTU_DISTRO=jammy
ARG ROS_DISTRO=humble
ARG OWNER=registry.auto.tuwien.ac.at/roblab/docker/$UBUNTU_DISTRO/$ROS_DISTRO
ARG BASE_CONTAINER=$OWNER-enviroment-base
FROM $BASE_CONTAINER

USER root


# setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743

# setup sources.list
RUN echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-latest.list && \
    wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

RUN apt-get update
RUN apt-get -y dist-upgrade

RUN apt-get install -y --no-install-recommends \
    gazebo \
    ros-$ROS_DISTRO-gazebo-ros2-control \
    ros-$ROS_DISTRO-gazebo-ros-pkgs    \
    ros-$ROS_DISTRO-gazebo-ros  
    
RUN rm -rf /var/lib/apt/lists/*

USER ${MY_USER}

ENV MY_PRJ=${MY_HOME}/projects/ros2/gazebo/

COPY --chown=${MY_USER}:${MY_USER} ./tmp/ws00 ${MY_PRJ}/ws00
RUN touch ${MY_PRJ}/ws00/src/gazebo_ros_pkgs/COLCON_IGNORE
RUN /bin/bash -c '. /opt/ros/${ROS_DISTRO}/setup.bash;  cd ${MY_PRJ}/ws00; colcon build --symlink-install'

COPY --chown=${MY_USER}:${MY_USER} ./tmp/ws01 ${MY_PRJ}/ws01
#RUN /bin/bash -c '. ${MY_PRJ}/ws00/install/setup.bash;  cd ${MY_PRJ}/wws01; colcon build --symlink-install'
RUN /bin/bash -c '. /opt/ros/${ROS_DISTRO}/setup.bash;  cd ${MY_PRJ}/ws01; colcon build --symlink-install'


COPY --chown=${MY_USER}:${MY_USER} ./env.sh ${MY_PRJ}/env.sh

RUN echo "ros2 service call /reset_simulation 'std_srvs/srv/Empty'" >> ~/.bash_history  && \   
    echo 'ros2 launch tuw_gazebo_models spawn_robot.launch.py model_name:=robot0 robot:=pioneer3dx  X:=-6.0 Y:=-6.0 Theta:=0.7' >> ~/.bash_history  && \   
    echo 'ros2 launch tuw_gazebo world.launch.py room:=cave' >> ~/.bash_history && \     
    echo 'tmux new -s gz \; split-window -v \; select-pane -t 1 \; split-window -v \; select-pane -t 0 \; attach' >> ~/.bash_history

USER ${MY_USER}
WORKDIR ${MY_PRJ}
ENV HOME=${MY_HOME}
CMD /bin/bash
