# enviroment desktop
# created by Markus Bader <markus.bader@tuwien.ac.at>
# created by Eugenn Kaltenegger <eugen.kaltenegger@tuwien.ac.at>

ARG OWNER=registry.auto.tuwien.ac.at/roblab/docker/focal/noetic
ARG BASE_CONTAINER=$OWNER-enviroment-core
FROM $BASE_CONTAINER

USER root


# setup keys
#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743

# setup sources.list
RUN echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-latest.list && \
    wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
    
RUN apt-get update
RUN apt-get -y dist-upgrade

RUN apt-get install -y --no-install-recommends \
    libgazebo11 \
    libgazebo11-dev \
    ros-$ROS_DISTRO-gazebo-ros-control \
    ros-$ROS_DISTRO-gazebo-ros-pkgs    \
    ros-$ROS_DISTRO-gazebo-ros  
    
RUN apt-get install -y ros-$ROS_DISTRO-gmapping \
	ros-$ROS_DISTRO-amcl  \
	ros-$ROS_DISTRO-map-server  \
	ros-$ROS_DISTRO-move-base  \
	ros-$ROS_DISTRO-navigation  \
	ros-$ROS_DISTRO-rviz \
	ros-$ROS_DISTRO-rviz
    
USER ${MY_USER}
ENV MY_PRJ=${MY_HOME}/projects/ros/gazebo/
RUN mkdir -p ${MY_PRJ}


COPY --chown=${MY_USER}:${MY_USER} ./tmp/ws00 ${MY_PRJ}/ws00
RUN /bin/bash -c '. /opt/ros/${ROS_DISTRO}/setup.bash;  cd ${MY_PRJ}/ws00; catkin_make'

COPY --chown=${MY_USER}:${MY_USER} ./tmp/ws01 ${MY_PRJ}/ws01
RUN /bin/bash -c '. ${MY_PRJ}/ws00/devel/setup.bash;  cd ${MY_PRJ}/ws01; catkin_make'


RUN cd ${MY_PRJ}/; ln -s ./ws01/src/tuw_gazebo/ide/env.sh
    
RUN echo 'if [ -f "env.sh" ]; then\n source env.sh \nelse\n echo "no env.sh to source" \nfi' >> ~/.bashrc

RUN echo 'ros2 launch tuw_gazebo_models spawn_robot.launch.py model_name:=robot0 robot:=pioneer3dx  X:=-6.0 Y:=-6.0 Theta:=0.7' >> ~/.bash_history  && \   
    echo 'ros2 launch tuw_gazebo world.launch.py room:=cave' >> ~/.bash_history && \     
    echo 'tmux new -s gz \; split-window -v \; select-pane -t 1 \; split-window -v \; select-pane -t 0 \; attach' >> ~/.bash_history

USER ${MY_USER}
WORKDIR ${MY_PRJ}
ENV HOME=${MY_HOME}
CMD /bin/bash
