
ARG OWNER=registry.auto.tuwien.ac.at/roblab/docker/bionic/melodic
ARG BASE_CONTAINER=$OWNER-enviroment-ide
FROM $BASE_CONTAINER

ENV INST_SCRIPTS=/tmp
ENV SRC_DIR=./mpn

ENV PROJECT_ROOT ${MY_HOME}/projects/mpn

USER root


# Install locale and set
RUN apt-get update &&  apt-get install -y git python3-pip \
   libmgl-dev libjsoncpp-dev autoconf libncurses5-dev libdxflib-dev \
   libgoogle-perftools-dev gperf

# ROS 
RUN apt-get install -y \
    ros-${ROS_DISTRO}-costmap-2d \
    ros-${ROS_DISTRO}-octomap \
    ros-${ROS_DISTRO}-octomap-msgs \
    ros-${ROS_DISTRO}-amcl \
    ros-${ROS_DISTRO}-laser-filters \
    ros-${ROS_DISTRO}-bfl \
    ros-${ROS_DISTRO}-cv-bridge \
    ros-${ROS_DISTRO}-move-base-msgs \
    ros-${ROS_DISTRO}-nav-core \
    ros-${ROS_DISTRO}-navfn \
    ros-${ROS_DISTRO}-map-server \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-robot-state-publisher \
    ros-${ROS_DISTRO}-pcl-ros  \
    ros-${ROS_DISTRO}-pcl-conversions \
    ros-${ROS_DISTRO}-rviz \
    ros-${ROS_DISTRO}-marker-msgs \
    ros-${ROS_DISTRO}-stage-ros
    
USER ${MY_USER}

RUN mkdir -p ${MY_HOME}/projects/mpn/ws00/src && \
    cd ${MY_HOME}/projects/mpn/ws00/src && \
    git clone --branch melodic https://github.com/tuw-robotics/grid_map.git  && \
    git clone --branch master https://github.com/tuw-robotics/tuw_msgs.git   && \
    git clone --branch master https://github.com/tuw-robotics/stage_ros.git  
    
RUN /bin/bash -c '. /opt/ros/${ROS_DISTRO}/setup.bash; cd ${MY_HOME}/projects/mpn/ws00; catkin_make' && \
    echo 'source ${MY_HOME}/projects/mpn/ws00/devel/setup.bash' >> ~/.bashrc

RUN mkdir -p ${MY_HOME}/projects/mpn/ws01/src && \
    cd ${MY_HOME}/projects/mpn/ws01/src && \
    git clone --branch master https://github.com/tuw-robotics/tuw_rviz.git && \
    git clone --branch master https://github.com/tuw-robotics/tuw_agv.git && \
    git clone --branch master https://github.com/tuw-robotics/tuw_control.git && \
    git clone --branch melodic https://github.com/tuw-robotics/tuw_geometry.git && \
    git clone --branch master https://github.com/tuw-robotics/tuw_teleop.git && \
    git clone --branch master https://github.com/tuw-robotics/tuw_collision_alarm.git && \
    git clone --branch master https://github.com/tuw-robotics/tuw_global_planner.git 
    
RUN /bin/bash -c '. ${MY_HOME}/projects/mpn/ws00/devel/setup.bash; cd ${MY_HOME}/projects/mpn/ws01; catkin_make' && \
    echo 'source ${MY_HOME}/projects/mpn/ws01/devel/setup.bash' >> ~/.bashrc

RUN mkdir -p ${MY_HOME}/projects/mpn/ws02/src && \
    cd ${MY_HOME}/projects/mpn/ws02/src && \
    git clone --branch melodic https://github.com/tuw-robotics/tuw_multi_robot.git
    
RUN /bin/bash -c '. ${MY_HOME}/projects/mpn/ws01/devel/setup.bash; cd ${MY_HOME}/projects/mpn/ws02; catkin_make' && \
    echo 'source ${MY_HOME}/projects/mpn/ws02/devel/setup.bash' >> ~/.bashrc

RUN echo "tmux new -s mrrp \; split-window -v \; split-window -v \; select-pane -t 0 \; attach" >> ~/.bash_history
RUN echo "roslaunch tuw_multi_robot_demo demo.launch room:=warehouse032  nr_of_robots:=14" >> ~/.bash_history
RUN echo "rosrun tuw_multi_robot_goal_generator goals_random _nr_of_robots:=32 _distance_boundary:=0.6 _distance_to_map_border:=0.2 _nr_of_avaliable_robots:=14" >> ~/.bash_history



# change https to ssh checkouts 
RUN cd ${MY_HOME}/projects/mpn && \
    find  -path '*/.git/config'  -exec sed -i 's/https:\/\/github.com\//git@github.com:/g' {} \;


# clean apt
USER root
RUN rm -rf /var/lib/apt/lists/*

USER ${MY_USER}
WORKDIR ${MY_HOME}
ENV HOME ${MY_HOME}
CMD /bin/bash
