# enviroment desktop
# created by Markus Bader <markus.bader@tuwien.ac.at>

ARG UBUNTU_DISTRO=jammy
ARG ROS_DISTRO=humble
ARG OWNER=registry.auto.tuwien.ac.at/roblab/docker/$UBUNTU_DISTRO/$ROS_DISTRO
ARG BASE_CONTAINER=$OWNER-enviroment-base
FROM $BASE_CONTAINER

USER root

USER ${MY_USER}

ENV MY_PRJ=${MY_HOME}/projects/ros2/nav2/

COPY --chown=${MY_USER}:${MY_USER} ./tmp/tuw ${MY_PRJ}/tuw
RUN /bin/bash -c '. /opt/ros/${ROS_DISTRO}/setup.bash;  cd ${MY_PRJ}/tuw; colcon build --symlink-install'


COPY --chown=${MY_USER}:${MY_USER} ./env.sh ${MY_PRJ}/env.sh

RUN echo 'ros2 run rviz2 rviz2 -d $(ros2 pkg prefix tuw2_launches)/share/tuw2_launches/config/rviz/nav2_default_view.rviz' >> ~/.bash_history && \     
    echo 'ros2 launch tuw2_launches nav2_launch.py use_sim_time:=True autostart:=False map:=/home/robot/projects/ros2/nav2/tuw/src/tuw2_launches/config/map/cave/map.yaml' >> ~/.bash_history && \     
    echo 'ros2 launch tuw2_launches laser_filter.launch.py ' >> ~/.bash_history && \     
    echo 'ros2 run mouse_teleop mouse_teleop --ros-args --remap mouse_vel:=cmd_vel' >> ~/.bash_history && \     
    echo 'tmux new -s gz \; split-window -v \; select-pane -t 1 \; split-window -v \; select-pane -t 0 \; attach' >> ~/.bash_history

USER ${MY_USER}
WORKDIR ${MY_PRJ}
ENV HOME=${MY_HOME}
CMD /bin/bash
