FROM tuw:noetic

ENV INST_SCRIPTS=/tmp
ENV SRC_DIR=./noetic-gz

# Replace 1000 with your user / group id
ARG MY_USER=robot
ARG MY_HOME=/home/${MY_USER}
ARG ROS_DISTRO=noetic
ENV MY_USER ${MY_USER}
ENV GZ_DIR /home/${MY_USER}/projects/gz

USER root
ADD ${SRC_DIR}/src/ ${INST_SCRIPTS}/
RUN find $INST_SCRIPTS -name '*.sh' -exec chmod a+x {} +


USER root
RUN apt-get update
RUM apt-install iputils-ping
RUN $INST_SCRIPTS/install_ros.sh  

USER ${MY_USER}
RUN mkdir -p ${GZ_DIR}/src/

# clean apt
USER root
#RUN rm -rf /var/lib/apt/lists/*
RUN chown -R ${MY_USER}:${MY_USER} ${MY_HOME}

USER ${MY_USER}
WORKDIR ${MY_HOME}
ENV HOME ${MY_HOME}
CMD /bin/bash

