FROM tuw:galactic

ENV INST_SCRIPTS=/tmp
ENV SRC_DIR=./galactic-mr

# Replace 1000 with your user / group id
ARG MY_USER=robot
ARG MY_HOME=/home/${MY_USER}
ENV MY_USER ${MY_USER}
ENV MR_DIR /home/${MY_USER}/projects/ros2/mr

USER root
ADD ${SRC_DIR}/src/ ${INST_SCRIPTS}/
RUN find $INST_SCRIPTS -name '*.sh' -exec chmod a+x {} +


USER root
RUN apt-get update
RUN $INST_SCRIPTS/install_stage.sh  

USER ${MY_USER}
RUN mkdir -p ${MR_DIR}/src/
COPY ${SRC_DIR}/utils/vscode.tar.gz ${MY_HOME}/ros2_ws
RUN cd ${MY_HOME}/ros2_ws && tar -xzvf *.tar.gz
	
RUN mkdir -p ${MR_DIR}/src/
	
RUN $INST_SCRIPTS/setup_mr.sh  

RUN echo "tmux new -s mpn \; split-window -v \; split-window -v \; select-pane -t 0 \; split-window -v \; select-pane -t 0 \; split-window -h \; select-pane -t 0 \; attach" >> ~/.bash_history
RUN echo "colcon build" >> ~/.bash_history
RUN echo "source $HOME/ros2_ws/install/setup.bash" >> ~/.bash_history
RUN echo "ros2 run stage_ros stageros $HOME/ros2_ws/src/world/willow-erratic.world" >> ~/.bash_history
RUN echo "ros2 run rqt_reconfigure rqt_reconfigure" >> ~/.bash_history
RUN echo "find -path */.git/config -exec sed -i 's/git@github.com:/https:\/\/github.com\//g' {} +" >> ~/.bash_history
RUN echo "find -path */.git/config -exec sed -i 's/https:\/\/github.com\//git@github.com:/g' {} +" >> ~/.bash_history
# clean apt
USER root
RUN rm -rf /var/lib/apt/lists/*
RUN chown -R ${MY_USER}:${MY_USER} ${MY_HOME}/projects ${MY_HOME}/ros*

USER ${MY_USER}
WORKDIR ${MY_HOME}
ENV HOME ${MY_HOME}
CMD /bin/bash

