ARG ROS_DISTRO=noetic

ARG INSTALL_SSH=true
ARG INSTALL_VNC=true
ARG INSTALL_IDE=true

FROM osrf/ros:${ROS_DISTRO}-desktop
RUN echo "ROS_DISTRO is on ${ROS_DISTRO}"

ENV INST_SCRIPTS=/tmp
ENV SRC_DIR=./base

# Replace 1000 with your user / group id
ARG MY_USER=robot
ARG MY_NAME="Robot"
ARG MY_PASSWORD="password"
ARG MY_UID=1000
ARG MY_GID=1000
ARG TZ=Europe/Vienna

ENV MY_USER=${MY_USER}
ENV MY_HOME=/home/${MY_USER}

USER root
RUN apt-get update && apt-get -y upgrade

# Install locale and set
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get install -y locales apt-utils
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY ${SRC_DIR}/utils/keyboard /etc/default/keyboard
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen; locale-gen

# Add user
ADD ${SRC_DIR}/src/add_user.sh ${INST_SCRIPTS}/add_user.sh
RUN chmod a+x ${INST_SCRIPTS}/add_user.sh
RUN $INST_SCRIPTS/add_user.sh 

# Install VNC-Server
USER root
COPY ${SRC_DIR}/src/install_turbovnc.sh ${INST_SCRIPTS}/install_turbovnc.sh
RUN chmod a+x ${INST_SCRIPTS}/install_turbovnc.sh
RUN if [ -z ${INSTALL_VNC} ]; then $INST_SCRIPTS/install_turbovnc.sh; fi

# Install some utils like vim, tmux, git, ...
USER root
ADD ${SRC_DIR}/src/install_utils.sh ${INST_SCRIPTS}/install_utils.sh
RUN chmod a+x ${INST_SCRIPTS}/install_utils.sh
RUN $INST_SCRIPTS/install_utils.sh

# Install IDE
USER root
COPY ${SRC_DIR}/src/install_ide.sh ${INST_SCRIPTS}/install_ide.sh
RUN chmod a+x ${INST_SCRIPTS}/install_ide.sh
RUN if [ -z ${INSTALL_IDE} ]; then $INST_SCRIPTS/install_ide.sh; fi

USER ${MY_USER}

RUN sed -i 's/01;32/01;31/g' ~/.bashrc # change bash colour to red
RUN echo "find -path */.git/config -exec sed -i 's/git@github.com:/https:\/\/github.com\//g' {} +" >> ~/.bash_history
RUN echo "find -path */.git/config -exec sed -i 's/https:\/\/github.com\//git@github.com:/g' {} +" >> ~/.bash_history

# clean apt
USER root
RUN rm -rf /var/lib/apt/lists/*
RUN chown -R ${MY_USER}:${MY_USER} ${MY_HOME}

USER ${MY_USER}
WORKDIR ${MY_HOME}
ENV HOME ${MY_HOME}
CMD /bin/bash
