# enviroment desktop
# created by Markus Bader <markus.bader@tuwien.ac.at>
# created by Eugenn Kaltenegger <eugen.kaltenegger@tuwien.ac.at>

FROM ros:galactic-ros1-bridge-focal

# Replace 1000 with your user / group id
ARG MY_USER=robot
ARG MY_NAME="Robot"
ARG MY_PASSWORD="password"
ARG MY_UID=1000
ARG MY_GID=1000
ARG TZ=Europe/Vienna

ENV MY_USER=${MY_USER}
ENV MY_HOME=/home/${MY_USER}


ENV CONFIG_DIR=./config
ENV SCRIPTS_DIR=./scripts
ENV DEB_DIR=./deb
ENV INSTALL_DIR=/install

USER root

RUN apt-get update && apt-get -y upgrade

# Install locale and set
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get install -y locales apt-utils
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen; locale-gen

# copy scripts to container
COPY ${SCRIPTS_DIR}/ ${INSTALL_DIR}/
# allow to run scripts in the container
RUN chmod -R a+x ${INSTALL_DIR}
# setup user
RUN $INSTALL_DIR/setup/add_user.sh
# make the user owner of the home directory

# copy bash history
COPY ${CONFIG_DIR}/bash/bash_history ${MY_HOME}/.bash_history
# copy keyboard config
COPY ${CONFIG_DIR}/keyboard/keyboard /etc/default/keyboard
# copy tmux config
COPY ${CONFIG_DIR}/tmux/tmux.conf ${MY_HOME}/.tmux.conf

RUN chown -R ${MY_USER}:${MY_USER} ${MY_HOME}
# install utils (like git, vim, nano, ...)
RUN apt-get install -y     \
      cmake            \
      cmake-curses-gui \
      curl             \
      git              \
      gnupg2           \
      keychain         \
      myrepos          \
      nano             \
      python3          \
      python3-pip      \
      rsync            \
      tmux             \
      vim              \
      wget
      
COPY ${DEB_DIR}/glow_1.4.1_linux_amd64.deb ${INSTALL_DIR}/
RUN dpkg -i ${INSTALL_DIR}/glow_1.4.1_linux_amd64.deb
    
RUN apt-get install -y openssh-server
RUN sed -ri 's/^#?Port\s+.*/Port 2222/' /etc/ssh/sshd_config

USER ${MY_USER}

RUN sed -i 's/01;32/01;31/g' ~/.bashrc # change bash colour to red
RUN echo 'if [ -f "env.sh" ]; then\n source env.sh \nelse\n echo "no env.sh to source" \nfi' >> ~/.bashrc

RUN echo "source /opt/ros/galactic/setup.bash" >> ~/.bash_history
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bash_history

COPY --chown=${MY_USER}:${MY_USER} ./bridge.md ${MY_HOME}/readme.md
USER root
# clean apt
RUN apt-get autoclean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

# setup entrypoint
COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]

USER ${MY_USER}
WORKDIR ${MY_HOME}
ENV HOME=${MY_HOME}
CMD /bin/bash
