FROM tuw:noetic

ENV INST_SCRIPTS=/tmp
ENV SRC_DIR=./noetic-mr

# Replace 1000 with your user / group id
ARG MY_USER=robot
ARG MY_HOME=/home/${MY_USER}
ARG ROS_DISTRO=noetic
ENV MY_USER ${MY_USER}
ENV MR_DIR /home/${MY_USER}/projects/mr

USER root
ADD ${SRC_DIR}/src/ ${INST_SCRIPTS}/
RUN find $INST_SCRIPTS -name '*.sh' -exec chmod a+x {} +


USER root
RUN apt-get update
RUM apt-install iputils-ping
RUN $INST_SCRIPTS/install_ros.sh  

USER ${MY_USER}
RUN mkdir -p ${MR_DIR}/src/
COPY ${SRC_DIR}/utils/kdev.tar.gz ${MR_DIR}/src/
COPY ${SRC_DIR}/utils/stage_ros-20.04.tar.gz ${MR_DIR}/src/
COPY ${SRC_DIR}/utils/mr2021.tar.gz ${MR_DIR}/src/
RUN cd ${MR_DIR}/src &&  \
	tar -xzvf kdev.tar.gz &&  \
	tar -xzvf mr2021.tar.gz  &&  \
	tar -xzvf stage_ros-20.04.tar.gz
	
RUN $INST_SCRIPTS/setup_mr.sh  

RUN echo "tmux new -s mpn \; split-window -v \; split-window -v \; select-pane -t 0 \; split-window -v \; select-pane -t 0 \; split-window -h \; select-pane -t 0 \; attach" >> ~/.bash_history
RUN echo "catkin_make -DCMAKE_BUILD_TYPE=Debug" >> ~/.bash_history
RUN echo "rosrun rqt_reconfigure rqt_reconfigure" >> ~/.bash_history
RUN echo "roslaunch stage_ros world.launch world:=line.world" >> ~/.bash_history
RUN echo "roslaunch mr_local_planner planner.launch world:=line.world mode:=1" >> ~/.bash_history
RUN echo "roslaunch stage_ros world.launch world:=cave.world" >> ~/.bash_history
RUN echo "roslaunch mr_local_planner planner.launch stage:=1 world:=cave.world mode:=1" >> ~/.bash_history
RUN echo "rm -rf ${MR_DIR}/src/mr* && git clone git@github.com:mx-teaching/mr-20.04.git ${MR_DIR}/src/mr" >> ~/.bash_history

# clean apt
USER root
RUN rm -rf /var/lib/apt/lists/*
RUN chown -R ${MY_USER}:${MY_USER} ${MY_HOME}

USER ${MY_USER}
WORKDIR ${MY_HOME}
ENV HOME ${MY_HOME}
CMD /bin/bash

